- name: Clone dotfiles
  shell: |
    git clone {{ dotfiles_repo }} ~/dotfiles
    sh ~/dotfiles/install.sh

- name: Setup fish
  shell: |
    echo /usr/local/bin/fish | sudo tee -a /etc/shells
    if [ ! grep -q /opt/homebrew/bin/fish /etc/shell ]; then
      chsh -s /opt/homebrew/bin/fish
    fi

- name: Setup neovim
  shell: |
    if [ ! -e ~/.local/share/nvim/site/pack/packer/start/packer.nvim ]; then
      git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    fi

- name: Setup anyenv
  shell: |
    echo y | anyenv install --init
    anyenv install pyenv
    anyenv install nodenv
    exec $SHELL -l
  ignore_errors: yes

- name: Setup pyenv
  shell: |
    pyenv install 3.9.4
    pyenv global 3.9.4
  ignore_errors: yes

- name: Setup nodenv
  shell: |
    nodenv install 16.17.1
    nodenv global 16.17.1
  ignore_errors: yes

- name: Setup neovim pt2
  shell: |
    python3 -m pip install --user --upgrade pynvim

- name: Add asdf erlang plugin
  shell: |
    asdf plugin add erlang
  ignore_errors: true

- name: Add asdf elixir plugin
  shell: |
    asdf plugin add elixir
  ignore_errors: true

- name: Install asdf erlang plugin
  shell: |
    asdf install erlang 25.1
    exec $SHELL -l
  ignore_errors: true

- name: Install asdf elixir plugin
  shell: |
    asdf install elixir 1.13.4-otp-25
    exec $SHELL -l
  ignore_errors: true

- name: Make asdf erlang plugins global
  shell: |
    asdf global erlang 25.1
    exec $SHELL -l
  ignore_errors: true

- name: Make asdf elixir plugin global
  shell: |
    asdf global elixir 1.13.4-otp-25
    exec $SHELL -l
  ignore_errors: true
