- name: Clone dotfiles
  shell: |
    git clone {{ dotfiles_repo }} ~/dotfiles
    sh ~/dotfiles/install.sh

- name: Setup fish
  shell: |
    echo /usr/local/bin/fish | sudo tee -a /etc/shells
    if grep -q /usr/local/bin/fish /etc/shell; then
      chsh -s /usr/local/bin/fish
    fi

- name: Setup neovim
  shell: |
    if [ ! -e ~/.local/share/nvim/site/pack/packer/start/packer.nvim ]; then
      git clone https://github.com/wbthomason/packer.nvim ~/.local/share/nvim/site/pack/packer/start/packer.nvim
    fi
