- name: Install OSX default settings
  osx_defaults:
    domain: "{{ item.domain }}"
    key: "{{ item.key }}"
    type: "{{ item.type }}"
    value: "{{ item.value }}"
    state: "{{ item.state }}"
  with_items:
  - "{{ osx_defaults }}"

- name: Configure the dock
  ansible.builtin.include_role:
    name: feffi.macos-dock
  vars:
    reset: true
    applications:
      add:
        - { label: "Mail", path: "" }
